#! /bin/sh
# This script is used by the db_backup container to create regular backups
# of the postgres database. 

pg_dumpall -U postgres -d postgres://db:5432 | sed "s/CREATE ROLE postgres;/-- CREATE ROLE postgres; -- already present in docker image/" | gzip -9 > /db_backups/`date +%Y-%m-%dT%H:%M:%S`.sql.gz
